new FFSim.Weapon("Wooden[N]", {attack:12,hit:0,crit:10,index:1});
new FFSim.Weapon("Small[K]", {attack:5,hit:10,crit:5,index:2});
new FFSim.Weapon("Wooden[R]", {attack:6,hit:0,crit:1,index:3});
new FFSim.Weapon("Rapier", {attack:9,hit:5,crit:10,index:4});
new FFSim.Weapon("Iron[H]", {attack:9,hit:0,crit:1,index:5});
new FFSim.Weapon("Short[S]", {attack:15,hit:10,crit:5,index:6});
new FFSim.Weapon("Hand[A]", {attack:16,hit:5,crit:3,index:7});
new FFSim.Weapon("Scimtar", {attack:10,hit:10,crit:5,index:8});
new FFSim.Weapon("Iron[N]", {attack:16,hit:0,crit:10,index:9});
new FFSim.Weapon("Large[K]", {attack:7,hit:10,crit:5,index:10});
new FFSim.Weapon("Iron[S]", {attack:14,hit:0,crit:1,index:11});
new FFSim.Weapon("Sabre", {attack:13,hit:5,crit:10,index:12});
new FFSim.Weapon("Long[S]", {attack:20,hit:10,crit:5,index:13});
new FFSim.Weapon("Great[A]", {attack:22,hit:5,crit:3,index:14});
new FFSim.Weapon("Falchon", {attack:15,hit:10,crit:5,index:15});
new FFSim.Weapon("Silver[K]", {attack:10,hit:15,crit:5,index:16});
new FFSim.Weapon("Silver[S]", {attack:23,hit:15,crit:5,index:17});
new FFSim.Weapon("Silver[H]", {attack:12,hit:5,crit:1,index:18});
new FFSim.Weapon("Silver[A]", {attack:25,hit:10,crit:4,index:19});
new FFSim.Weapon("Flame[S]", {attack:26,hit:20,crit:5,index:20});
new FFSim.Weapon("Ice[S]", {attack:29,hit:25,crit:5,index:21});
new FFSim.Weapon("Dragon[S]", {attack:19,hit:15,crit:10,index:22});
new FFSim.Weapon("Giant[S]", {attack:21,hit:20,crit:5,index:23});
new FFSim.Weapon("Sun[S]", {attack:32,hit:30,crit:5,index:24});
new FFSim.Weapon("Coral[S]", {attack:19,hit:15,crit:10,index:25});
new FFSim.Weapon("Were[S]", {attack:18,hit:15,crit:5,index:26});
new FFSim.Weapon("Rune[S]", {attack:18,hit:15,crit:5,index:27});
new FFSim.Weapon("Power[R]", {attack:12,hit:0,crit:1,index:28});
new FFSim.Weapon("Light[A]", {attack:28,hit:15,crit:3,index:29},{spell:"HRM2"});
new FFSim.Weapon("Heal[R]", {attack:6,hit:0,crit:1,index:30},{spell:"HEAL"});
new FFSim.Weapon("Mage[R]", {attack:12,hit:10,crit:1,index:31},{spell:"FIR2"});
new FFSim.Weapon("Defense", {attack:30,hit:35,crit:5,index:32},{spell:"RUSE"});
new FFSim.Weapon("Wizard[R]", {attack:15,hit:15,crit:1,index:33},{spell:"CONF"});
new FFSim.Weapon("Vorpal", {attack:24,hit:25,crit:30,index:34});
new FFSim.Weapon("CatClaw", {attack:22,hit:35,crit:5,index:35});
new FFSim.Weapon("Thor[H]", {attack:18,hit:15,crit:1,index:36},{spell:"LIT2"});
new FFSim.Weapon("Bane[S]", {attack:22,hit:20,crit:10,index:37},{spell:"BANE"});
new FFSim.Weapon("Katana", {attack:33,hit:35,crit:30,index:38});
new FFSim.Weapon("Xcalber", {attack:45,hit:35,crit:5,index:39});
new FFSim.Weapon("Masmune", {attack:56,hit:50,crit:10,index:40});

new FFSim.Armor("Cloth",{def:1,weight:3});
new FFSim.Armor("Wooden[A]",{def:4,weight:8});
new FFSim.Armor("Chain[A]",{def:15,weight:15});
new FFSim.Armor("Iron[A]",{def:24,weight:23});
new FFSim.Armor("Steel[A]",{def:34,weight:33});
new FFSim.Armor("Silver[A]",{def:18,weight:8});
new FFSim.Armor("Flame[A]",{def:34,weight:10},{element:FFSim.Ice});
new FFSim.Armor("Ice[A]",{def:34,weight:10},{element:FFSim.Fire});
new FFSim.Armor("Opal[A]",{def:42,weight:10},{element:FFSim.Lightning});
new FFSim.Armor("Dragon[A]",{def:42,weight:10},{element:[FFSim.Fire,FFSim.Ice,FFSim.Lightning]});
new FFSim.Armor("Copper[B]",{def:4,weight:1});
new FFSim.Armor("Silver[B]",{def:15,weight:1});
new FFSim.Armor("Gold[B]",{def:24,weight:1});
new FFSim.Armor("Opal[B]",{def:34,weight:1});
new FFSim.Armor("White[R]",{def:24,weight:2},{element:[FFSim.Fire,FFSim.Death],spell:"INV2"});
new FFSim.Armor("Black[R]",{def:24,weight:2},{element:[FFSim.Ice,FFSim.Time],spell:"ICE2"});
new FFSim.Armor("Wooden[S]",{def:2,weight:0});
new FFSim.Armor("Iron[S]",{def:4,weight:0});
new FFSim.Armor("Silver[S]",{def:8,weight:0});
new FFSim.Armor("Flame[S]",{def:12,weight:0},{element:FFSim.Ice});
new FFSim.Armor("Ice[S]",{def:12,weight:0},{element:FFSim.Fire});
new FFSim.Armor("Opal[S]",{def:16,weight:0},{element:FFSim.Lightning});
new FFSim.Armor("Aegis[S]",{def:16,weight:0},{element:FFSim.PoisonStone});
new FFSim.Armor("Buckler",{def:2,weight:0});
new FFSim.Armor("ProCape",{def:8,weight:2});
new FFSim.Armor("Cap",{def:1,weight:1});
new FFSim.Armor("Wooden[H]",{def:3,weight:3});
new FFSim.Armor("Iron[H]",{def:5,weight:5});
new FFSim.Armor("Silver[H]",{def:6,weight:3});
new FFSim.Armor("Opal[H]",{def:8,weight:3});
new FFSim.Armor("Heal[H]",{def:6,weight:3},{spell:"HEAL"});
new FFSim.Armor("Ribbon",{def:1,weight:1},{element:FFSim.AllElements});
new FFSim.Armor("Gloves",{def:1,weight:1});
new FFSim.Armor("Copper[G]",{def:2,weight:3});
new FFSim.Armor("Iron[G]",{def:4,weight:5});
new FFSim.Armor("Silver[G]",{def:6,weight:3});
new FFSim.Armor("Zeus[G]",{def:6,weight:3},{spell:"LIT2"});
new FFSim.Armor("Power[G]",{def:6,weight:3},{spell:"SABR"});
new FFSim.Armor("Opal[G]",{def:8,weight:3});
new FFSim.Armor("ProRing",{def:8,weight:1},{element:FFSim.Death});